## Day 1 – NumPy Arrays & Operations
Dataset: HR Employee Attrition
Goal: Practice NumPy arrays and basic numerical exploration.


In [20]:

import numpy as np
import pandas as pd

## Load the HR dataset


In [21]:
df = pd.read_excel("/content/HR-Employee-Attrition.xlsx")

print("Dataset shape:", df.shape)

Dataset shape: (1470, 35)


## Select numerical columns


In [22]:
numeric_data = df.select_dtypes(include=np.number)

## 1D array


In [8]:
age_1d = df["Age"].to_numpy()
print(age_1d[:10])

[41 49 37 33 27 32 59 30 38 36]


## 2D array

In [23]:
age_income_2d = df[["Age", "MonthlyIncome"]].to_numpy()
print(age_income_2d[:5])

[[  41 5993]
 [  49 5130]
 [  37 2090]
 [  33 2909]
 [  27 3468]]


## 3D array


## Create 3 layers using Age, MonthlyIncome and TotalWorkingYears.


In [24]:
first_10 = df[["Age", "MonthlyIncome", "TotalWorkingYears"]].to_numpy()[:10]
array_3d = np.stack([first_10, first_10, first_10])
print("\n3D Array shape:", array_3d.shape)


3D Array shape: (3, 10, 3)


## Addition, subtraction, multiplication and division


In [11]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])

In [13]:
print("\nAddition:", a + b)


Addition: [12 24 35 48 60]


In [14]:
print("Subtraction:", a - b)

Subtraction: [ 8 16 25 32 40]


In [15]:
print("Multiplication:", a * b)

Multiplication: [ 20  80 150 320 500]


In [16]:
print("Division:", a / b)

Division: [5. 5. 6. 5. 5.]


## NumPy functions


In [17]:
print("\nMean Age:", np.mean(age_1d))


Mean Age: 36.923809523809524


In [18]:
print("Total Age:", np.sum(age_1d))

Total Age: 54278


In [19]:
print("Age Standard Deviation:", np.std(age_1d))

Age Standard Deviation: 9.132265690615387


## reshape()


In [27]:
sample = np.arange(1, 13)

In [28]:
reshaped = sample.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## arange()


In [29]:
numbers = np.arange(0, 21, 5)
print("\narange():", numbers)


arange(): [ 0  5 10 15 20]


## linspace()


In [30]:
line_numbers = np.linspace(0, 100, 6)
print("linspace():", line_numbers)

linspace(): [  0.  20.  40.  60.  80. 100.]


## Find indices of maximum and minimum Age


In [31]:
max_index = np.argmax(age_1d)
min_index = np.argmin(age_1d)

In [32]:
print("\nIndex of maximum Age:", max_index)


Index of maximum Age: 411


In [33]:
print("Maximum Age:", age_1d[max_index])

Maximum Age: 60


In [34]:
print("Index of minimum Age:", min_index)

Index of minimum Age: 296


In [35]:
print("Minimum Age:", age_1d[min_index])

Minimum Age: 18
